CUDA_VISIBLE_DEVICES=0,1 python main.py \
    --device cuda \
    --dataset CIFAR10 --protocal I \
    --notes "cifar10_i/ablation_without/16bits" \
    --trainable_layer_num 2 \
    --M 2 \
    --feat_dim 32 \
    --T 0.2 \
    --tau_cqc 0.2 \
    --prot_loss_weight 0.5 \
    --hp_beta 5e-3 \
    --softmax_temp 5.0 \
    --clip_r 0.7 \
    --init_neg_curvs 1.0 \
    --full_hyperpq \
    --disable_writer \
    --epoch_num 50 \
    --clus_mode "hier_clus" \
    --num_clus_list "200,100,50" \
    --warmup_epoch 3 \
    --eval_interval 2 \
    --topK 1000 \
    --checkpoint_dir ./checkpoints/cifar10_i/ablation_without/16bits \

